name: Bug Report
description: Report an Issue or Bug with the Package
title: "[Bug]: "
labels: ["bug"]
projects:
  -
assignees:
body:
  - type: markdown
    attributes:
      value: |
        We're sorry to hear you're having a problem. Please help us solve it by providing the following details.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: I cannot currently do X because when I try, it breaks Y.
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce the bug
      description: How did this occur? Please include any config values used and provide reliable steps if possible.
      placeholder: When I do X, I see Y.
    validations:
      required: true
  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: Which version of our package are you running? Please be as specific as possible.
      placeholder: 2.0.0
    validations:
      required: true
  - type: input
    id: php-version
    attributes:
      label: PHP Version
      description: Which version of PHP are you running? Please be as specific as possible.
      placeholder: 8.2.0
    validations:
      required: true
  - type: input
    id: laravel-version
    attributes:
      label: Laravel Version
      description: Which version of Laravel are you running? Please be as specific as possible.
      placeholder: 9.0.0
    validations:
      required: true
  - type: dropdown
    id: database
    attributes:
      label: Which database does this happen with?
      multiple: false
      options:
        - MySQL
        - SQLite
        - MariaDB
        - PostgreSQL
        - SQL Server
    validations:
      required: true
  - type: input
    id: database-version
    attributes:
      label: Database Version
      description: Which version of the database are you running? Please be as specific as possible.
      placeholder: 5.7
    validations:
      required: true
  - type: dropdown
    id: operating-systems
    attributes:
      label: Which operating systems does this occur with?
      description: You may select more than one.
      multiple: true
      options:
        - macOS
        - Windows
        - Linux
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Use this field to provide any additional information that might be relevant to the issue.
    validations:
      required: false
