name: tests-for-postgres

on:
  push:
    paths:
      - "**.php"
      - ".github/workflows/tests-for-laravel-versions.yml"
      - ".github/workflows/tests-for-sql-server.yml"
      - ".github/workflows/tests-for-postgres.yml"
      - ".github/workflows/test-for-mariadb.yml"
      - ".github/workflows/tests-for-mysql.yml"
      - ".github/workflows/tests-for-mysql8.yml"
      - "phpunit.xml.dist"
      - "composer.json"
      - "composer.lock"
  workflow_dispatch:

jobs:
  pgsql:
    runs-on: ubuntu-24.04

    services:
      postgresql:
        image: postgres:14
        env:
          POSTGRES_DB: laravel
          POSTGRES_USER: forge
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd=pg_isready --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: true

    name: PostgreSQL 14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_pgsql, :php-psr
          tools: composer:v2
          coverage: none

      - name: Set Framework version
        run: composer config version "11.x-dev"

      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit
        env:
          DB_CONNECTION: pgsql
          DB_USERNAME: forge
          DB_PASSWORD: password
